### ISSUE TITLE
How to get this started with the new API?

### ISSUE THREAD

**Issue by Jarrio** [RaidAndFade/Haxicord#22]
Both the command example in the `README.md` and the "normal users" examples do not run, what happens is the application opens, runs through the commands and instantly exits with nothing blocking. I can't use `client.start()` cause that's deprecated now and I tried artificially blocking with `while(true) {}` but that also gave me no `onReady` callback

**Comment by RaidAndFade** [comment]
User joined support server and got issue resolved. Closing issue.
